server:
  port: 8080
spring:
  thymeleaf:
    cache: false
  jpa:
    database: mysql
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/starlink
    username: root
    password: bdacccw
    driver-class-name: com.mysql.jdbc.Driver
    ddl-auto: update
    hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

